### ISSUE TITLE
Api.clj missing?

### ISSUE THREAD

**Issue by jellea** [kieranbrowne/clojure-tensorflow-interop#1]
First of all, great work! Can't wait to give this a spin!

```
CompilerException java.io.FileNotFoundException: Could not locate clojure_tensorflow_interop/api__init.class or clojure_tensorflow_interop/api.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name., compiling:(clojure_tensorflow_interop/helpers.clj:1:1)
```

Tried removing the namespace declaration, but it seems its actually in use. Did you maybe forget to commit it?

Thanks!

**Comment by jellea** [comment]
Have some other fixes on a branch as well if you're interested: 
https://github.com/jellea/clojure-tensorflow-interop/tree/fixes

**Comment by kieranbrowne** [comment]
Definitely! Send me a pull request?

**Comment by kieranbrowne** [comment]
Actually don't worry I already did it.
Thanks for all your help! 🥇
